language: c

compiler: gcc

env:
    global:
        - SDK=0.9.1
        - SANITYCHECK_OPTIONS=" --inline-logs -R"
        - SANITYCHECK_OPTIONS_RETRY=" --inline-logs --only-failed --outdir=out-2nd-pass"
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.9.1
        - ZEPHYR_GCC_VARIANT=zephyr
        - USE_CCACHE=1
        - COVERAGE="--all --enable-slow"
        - MATRIX_BUILDS="6"
    matrix:
        - MATRIX_BUILD="1"
        - MATRIX_BUILD="2"
        - MATRIX_BUILD="3"
        - MATRIX_BUILD="4"
        - MATRIX_BUILD="5"
        - MATRIX_BUILD="6"

build:
    cache: true
    cache_dir_list:
        - ${SHIPPABLE_BUILD_DIR}/ccache
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: master.16
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - export CCACHE_DIR=${SHIPPABLE_BUILD_DIR}/ccache/.ccache
      - git submodule update --remote
      - cd zephyr
      - source zephyr-env.sh
      - ccache -c -s --max-size=5000M
      - make host-tools
      - export PREBUILT_HOST_TOOLS=${ZEPHYR_BASE}/bin
      - >
          if [ "$JOB_TRIGGERED_BY_NAME" = "undefined" ]; then
            LOG_TYPE="manual";
          else
            LOG_TYPE=${JOB_TRIGGERED_BY_NAME};
          fi;

          S3_PATH="s3://zephyr-logs/${LOG_TYPE}/${REPO_FULL_NAME}/${BUILD_NUMBER}";
      - >
          if [ "$JOB_TRIGGERED_BY_NAME" = "daily-verify" ]; then
            echo "- Building with -R --all --enable-slow";
            COVERAGE="--all --enable-slow";
          fi;
      - >
        ./scripts/sanitycheck --subset ${MATRIX_BUILD}/${MATRIX_BUILDS} ${COVERAGE} ${SANITYCHECK_OPTIONS};
        if [ "$?" != "0" ]; then
          sleep 10;
          ./scripts/sanitycheck --subset ${MATRIX_BUILD}/${MATRIX_BUILDS} ${COVERAGE} ${SANITYCHECK_OPTIONS_RETRY};
        fi;
      - ccache -s
    post_ci:
      - rm -rf sanity-out out-2nd-pass
      - mkdir -p ../shippable/testresults
      - >
        if [ -e compliance.xml ]; then
          cp compliance.xml ../shippable/testresults/;
          aws s3 cp compliance.xml ${S3_PATH}/;
        fi;
      - >
        if [ -e ./scripts/sanity_chk/last_sanity.xml ]; then
          cp ./scripts/sanity_chk/last_sanity.xml ../shippable/testresults/;
          aws s3 cp ./scripts/sanity_chk/last_sanity.xml ${S3_PATH}/sanitycheck.xml;
        fi;

integrations:
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - builds@zephyrproject.org
      branches:
        only:
          - master
          - net
          - bluetooth
          - arm
      on_success: never
      on_failure: never
