language: c

compiler: gcc

env:
    global:
        - SDK=0.9.2
        - SANITYCHECK_OPTIONS=" --inline-logs -R"
        - SANITYCHECK_OPTIONS_RETRY=" --inline-logs --only-failed --outdir=out-2nd-pass"
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.9.2
        - ZEPHYR_GCC_VARIANT=zephyr
        - USE_CCACHE=1
        - COVERAGE="--all --enable-slow"
        - QEMU_BIN_PATH=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/
        - QEMU_BIOS=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/share/qemu
        - DTC=${ZEPHYR_SDK_INSTALL_DIR}/sysroots/x86_64-pokysdk-linux/usr/bin/dtc
        - MATRIX_BUILDS="8"
    matrix:
        - MATRIX_BUILD="1"
        - MATRIX_BUILD="2"
        - MATRIX_BUILD="3"
        - MATRIX_BUILD="4"
        - MATRIX_BUILD="5"
        - MATRIX_BUILD="6"
        - MATRIX_BUILD="7"
        - MATRIX_BUILD="8"

build:
    cache: true
    cache_dir_list:
        - ${SHIPPABLE_BUILD_DIR}/ccache
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: v0.2
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - export CCACHE_DIR=${SHIPPABLE_BUILD_DIR}/ccache/.ccache
      - git submodule update --remote
      - cd zephyr
      - source zephyr-env.sh
      - ccache -c -s --max-size=5000M
      - >
          if [ "$JOB_TRIGGERED_BY_NAME" = "undefined" ]; then
            LOG_TYPE="manual";
          else
            LOG_TYPE=${JOB_TRIGGERED_BY_NAME};
          fi;

          S3_PATH="s3://zephyr-logs/${LOG_TYPE}/${REPO_FULL_NAME}/${BUILD_NUMBER}";
      - >
          if [ "$JOB_TRIGGERED_BY_NAME" = "daily-verify" ]; then
            echo "- Building with -R --all --enable-slow";
            COVERAGE="--all --enable-slow";
          elif [ "$JOB_TRIGGERED_BY_NAME" = "daily-verify-debug" ]; then
            export CONFIG_DEBUG=y
            echo "- Building with -R --all --enable-slow";
            COVERAGE="--all --enable-slow";
          elif [ "$JOB_TRIGGERED_BY_NAME" = "daily-verify-issm" ]; then
            echo "- Building with ISSM";
            export ISSM_INSTALLATION_PATH=/opt/toolchain/issm
            export ZEPHYR_GCC_VARIANT=issm
          elif [ "$JOB_TRIGGERED_BY_NAME" = "code-scan" ]; then
            wget -q https://scan.coverity.com/download/linux64 --post-data "token=${COVERITY_TOKEN}&project=Zephyr" -O coverity_tool.tgz
            tar xvf coverity_tool.tgz;
            rm -f coverity_tool.tgz;
            mv cov-*  cov-analysis;
            export PATH=$PATH:${PWD}/cov-analysis/bin

            cov-configure --comptype gcc --compiler i586-zephyr-elfiamcu-gcc --template
            cov-configure --comptype gcc --compiler arm-zephyr-eabi-gcc --template
            cov-configure --comptype gcc --compiler arc-zephyr-elf-gcc --template

            export COVERAGE="-a arc -a arm -a x86"
            cov-build --dir ${SHIPPABLE_BUILD_DIR}/cov-build/cov-int ./scripts/sanitycheck --subset ${MATRIX_BUILD}/${MATRIX_BUILDS} ${COVERAGE} ${SANITYCHECK_OPTIONS};

            GIT_VERSION=$(git describe)
            aws s3 sync --quiet  ${SHIPPABLE_BUILD_DIR}/cov-build/cov-int  s3://coverity.zephyrproject.org/weekly/

          elif [ "$JOB_TRIGGERED_BY_NAME" = "daily-verify-arm" ]; then
            echo "- Building with ARM cross toolchain";
            export GCCARMEMB_TOOLCHAIN_PATH=/opt/toolchain/arm-none-eabi
            export ZEPHYR_GCC_VARIANT=gccarmemb
          fi;
      - >
        if [ "$JOB_TRIGGERED_BY_NAME" != "code-scan" ]; then
          ./scripts/sanitycheck --subset ${MATRIX_BUILD}/${MATRIX_BUILDS} ${COVERAGE} ${SANITYCHECK_OPTIONS};
          if [ "$?" != "0" ]; then
            sleep 10;
            ./scripts/sanitycheck ${COVERAGE} ${SANITYCHECK_OPTIONS_RETRY};
          fi;
        fi
      - ccache -s
    on_success:
      - rm -rf sanity-out out-2nd-pass
      - mkdir -p ../shippable/testresults
      - >
        if [ -e ./scripts/sanity_chk/last_sanity.xml ]; then
          cp ./scripts/sanity_chk/last_sanity.xml ../shippable/testresults/;
          aws s3 cp ./scripts/sanity_chk/last_sanity.xml ${S3_PATH}/sanitycheck.xml;
        fi;
    on_failure:
      - rm -rf sanity-out out-2nd-pass
      - mkdir -p ../shippable/testresults
      - >
        if [ -e ./scripts/sanity_chk/last_sanity.xml ]; then
          cp ./scripts/sanity_chk/last_sanity.xml ../shippable/testresults/;
          aws s3 cp ./scripts/sanity_chk/last_sanity.xml ${S3_PATH}/sanitycheck.xml;
        fi;

integrations:
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - zephyr-builds@lists.zephyrproject.org
      branches:
        only:
          - master
      on_success: never
      on_failure: always
