language: c

compiler: gcc

env:
    global:
        - SDK=0.9
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.9
        - ZEPHYR_GCC_VARIANT=zephyr
        - USE_CCACHE=1
    matrix:
        - MATRIX_BUILD="1"

build:
    cache: true
    cache_dir_list:
        - ${SHIPPABLE_BUILD_DIR}/ccache
    pre_ci_boot:
        image_name: nashif/zephyr
        image_tag: master.6
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - export CCACHE_DIR=${SHIPPABLE_BUILD_DIR}/ccache/.ccache
      - git submodule update --remote
      - cd zephyr
      - source zephyr-env.sh
      - git clone https://github.com/zephyrproject-rtos/docs-theme.git doc/themes/zephyr-docs-theme
      - make DOC_TAG=daily htmldocs
    on_success:
      - aws s3 sync --quiet --delete doc/_build/html s3://zephyr-docs/online/dev

integrations:
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - builds@zephyrproject.org
      branches:
        only:
          - master
      on_success: never
      on_failure: never
